spring:
  application:
    name: techstore

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TEStore;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: trungdinh.dev@gmail.com
    password: bpwy zooq odye mnqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

api:
  prefix: api/v1

jwt:
  secretKey: QFj6plpOzUysQzNFGQwdZRMpebEpCicqSknkcg2Kx0E=
  expiration: 86400000

